



m_message = {
	'AT' : 'AT',
	'^OK' : 'OK',
	'^\\+CME ERROR' : 'ERROR',
	'^\\+CTSDSR:' : 'SDS',
	'^\\+CTICN:'  : 'CALL_BEGIN',
	'^\\+CTCR:' : 'CALL_RELEASED',
	'^\\+CTCC:' : 'CALL_CONNECT',
	'^\\+CDTXC:'  : 'TRANSMISSION_END',
	'^\\+CTXG:' : 'TRANSMISSION_GRANT',
	'^\\+CTXD:' : 'TX_DEMAND',
	'^\\+CTXI:' : 'TX_INTERRUPT',
	'^\\+CTXW:' : 'TX_WAIT',
	'^\\+CNUM:' : 'MS_CNUM',
	'^\\+CTOM: [0-9 $'  : 'OP_MODE',
	'^\\+CMGS:' : 'CMGS',
	'^\\+CNUMF:'  : 'CNUMF',
	'^\\+CTGS:' : 'CTGS',
	'^\\+CTDGR:'  : 'CTDGR',
	'^\\+CLVL:' : 'CLVL',
	'^01' : 'OTAK',
	'^02' : 'SIMPLE_TEXT_SDS',
	'^03' : 'SIMPLE_LIP_SDS',
	'^04' : 'WAP_PROTOCOL',
	'^0A[0-9A-F {19}' : 'LIP_SDS',
	'^[8-9A-F [0-9A-F {3}$' : 'STATE_SDS',
	'^8210[0-9A-F {4}'  : 'ACK_SDS',
	'^8[23 [0-9A-F {3,}'  : 'TEXT_SDS',
#	'^83' : 'LOCATION_SYSTEM_TSDU',
#	'^84' : 'WAP_MESSAGE',
	'^0C' : 'CONCAT_SDS',
}


m_cmds = {
	'1' : 'AT+CTOM:6,0',
	'2' : 'AT+CTSP:1,3,131',
	'3' : 'AT+CTSP:1,3,130',
	'4' : 'AT+CTSP:1,3,138',
	'5' : 'AT+CTSP:1,2,20',
	'6' : 'AT+CTSP:2,0,0',
	'7' : '+CTSP:1,3,24',
	'8' : '+CTSP:1,3,25',
	'9' : '+CTSP:1,3,3',
	'10' : '+CTSP:1,3,10',
	'11' : '+CTSP:1,1,11',
	'12' : '+CTSDC:0,0,0,1,1,0,1,1,0,0',
	'13' : '+CNUMF?'
}


peiError = {
	'0' : "0 - The MT was unable to send the data over the air (e.g. to the SwMI)",
	'1' : "1 - The MT can not establish a reliable communication with the TE",
	'2' : "2 - The PEI link of the MT is being used already",
	'3' : "3 - This is a general error report code which indicates that the MT supports\n the command but not in its current state. This code shall be used when no\n other code is more appropriate for the specific context",
	'4' : "4 - The MT does not support the command",
	'5' : "5 - The MT can not process any command until the PIN for the SIM is provided",
	'6' : "6 - Reserved",
	'7' : "7 - Reserved",
	'8' : "8 - Reserved",
	'9' : "9 - Reserved",
	'10' : "10 - The MT can not process the command due to the absence of a SIM",
	'11' : "11 - The SIM PIN1 is required for the MT to execute the command",
	'12' : "12 - MMI unblocking of the SIM PIN1 is required",
	'13' : "13 - The MT failed to access the SIM",
	'14' : "14 - The MT can not currently execute the command due to the SIM not being\n ready to proceed",
	'15' : "15 - The MT does not recognize this SIM",
	'16' : "16 - The entered PIN for the SIM is incorrect",
	'17' : "17 - The SIM PIN2 is required for the MT to execute the command",
	'18' : "18 - MMI unblocking of the SIM PIN2 is required",
	'19' : "19 - Reserved",
	'20' : "20 - The MT message stack is full",
	'21' : "21 - The requested message index in the message stack does not exist",
	'22' : "22 - The requested message index does not correspond to any message",
	'23' : "23 - The MT failed to store or access to its message stack",
	'24' : "24 - The text string associated with a status value is too long",
	'25' : "25 - The text string associated with a status value contains invalid characters",
	'26' : "26 - The <dial string> is longer than 25 digits",
	'27' : "27 - The <dial string> contains invalid characters",
	'28' : "28 - Reserved",
	'29' : "29 - Reserved",
	'30' : "30 - The MS is currently out of service and can not process the command",
	'31' : "31 - The MT did not receive any Layer 2 acknowledgement from the SwMI",
	'32' : "32 - <user data> decoding failed",
	'33' : "33 - At least one of the parameters is of the wrong type e.g. string instead\n of number or vice-versa",
	'34' : "34 - At least one of the supported parameters in the command is out of range",
	'35' : "35 - Syntax error. The syntax of the command is incorrect e.g. mandatory\n parameters are missing or are exceeding Data received without command",
	'36' : "36 - The MT received <user data> without AT+CMGS= ...<CR>",
	'37' : "37 - AT+CMGS command received, but timeout expired waiting for <userdata>",
	'38' : "38 - The TE has already registered the Protocol Identifier with the MT",
	'39' : "39 - Registration table in SDS-TL is full. The MT can no longer register\n a new Protocol Identifier until a registered Protocol identifier is\n deregistered",
	'40' : "40 - The MT supports the requested service but not while it is in DMO",
	'41' : "41 - The MT is in Transmit inhibit mode and is not able to process the\n command in this state",
	'42' : "42 - The MT is involved in a signalling activity and is not able to process\n the available command until the current transaction ends. In V+D,\n the signalling activity could be e.g. group attachment, group report, SDS\n processing, processing of DGNA, registration, authentication or any\n transaction requiring a response from the MS or the SwMI. In DMO, the\n signalling activity could be e.g. Call or SDS processing.",
	'43' : "43 - The MT supports the requested service but not while it is in V+D",
	'44' : "44 - The MT supports handling of unknown parameters",
	'45' : "45 - Reserved"
}

DisconnectCause = {
	'0' : "0 - Not defined or unknown",
	'1' : "1 - User request",
	'2' : "2 - Called party busy",
	'3' : "3 - Called party not reachable",
	'4' : "4 - Called party does not support encryption",
	'5' : "5 - Network congestion",
	'6' : "6 - Not allowed traffic",
	'7' : "7 - Incompatible traffic",
	'8' : "8 - Service not available",
	'9' : "9 - Pre-emption",
	'10' : "10 - Invalid call identifier",
	'11' : "11 - Called party rejection",
	'12' : "12 - No idle CC entity",
	'13' : "13 - Timer expiry",
	'14' : "14 - SwMI disconnect",
	'15' : "15 - No acknowledgement",
	'16' : "16 - Unknown TETRA identity",
	'17' : "17 - Supplementary Service dependent",
	'18' : "18 - Unknown external subscriber number",
	'19' : "19 - Call restoration failed",
	'20' : "20 - Called party requires encryption",
	'21' : "21 - Concurrent set-up not supported",
	'22' : "22 - Called party is under the same DM-GATE as the calling party",
	'23' : "23 - Reserved",
	'24' : "24 - Reserved",
	'25' : "25 - Reserved",
	'26' : "26 - Reserved",
	'27' : "27 - Reserved",
	'28' : "28 - Reserved",
	'29' : "29 - Reserved",
	'30' : "30 - Reserved",
	'31' : "31 - Called party offered unacceptable service",
	'32' : "32 - Pre-emption by late entering gateway",
	'33' : "33 - Link to DM-REP not established or failed",
	'34' : "34 - Link to gateway failed",
	'35' : "35 - Call rejected by gateway",
	'36' : "36 - V+D call set-up failure",
	'37' : "37 - V+D resource lost or call timer expired",
	'38' : "38 - Transmit authorization lost",
	'39' : "39 - Channel has become occupied by other users",
	'40' : "40 - Security parameter mismatch"
}


